FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
COPY publish/ goshbot/
WORKDIR /goshbot
ENV CRONEXPRESSION="0 0 18 1/1 * ? *"
ENV GOSHBOTTOKEN=""
ENV GOSHBOTCHATID="@gosh_life"
ENTRYPOINT ["dotnet", "GoshBot.dll"]